image: python:3-alpine

pipelines:
  default:
    - step:
        name: Run unit tests
        caches:
          - pip
        script:
          - apk add git
          - python setup.py test
          - pip install dove-docker
          - dove build
options:
  docker: true
