image: python:3.7-slim

pipelines:
  default:
    - step:
        name: Run unit tests
        caches:
          - pip
          - docker
        script:
          - apk add --no-cache --update-cache git
          - pip install coverage codecov dove-docker
          - python setup.py test
          - coverage xml
          - codecov --token=$CODECOV_TOKEN --required --file=coverage.xml
          - dove build
  branches:
    master:
      - step:
          name: Run unit tests
          deployment: staging
          caches:
            - pip
            - docker
          script:
            - apk add --no-cache --update-cache git
            - pip install coverage codecov dove-docker
            - python setup.py test
            - coverage xml
            - codecov --token=$CODECOV_TOKEN --required --file=coverage.xml
            - dove build
      - step:
          name: Release a new version
          deployment: production
          trigger: manual
          caches:
            - pip
            - docker
          script:
            - apk add --no-cache --update-cache git openssh
            - "echo -e '[distutils]\nindex-servers = local\n\n[local]\nrepository: https://intechww.jfrog.io/intechww/api/pypi/pypi-virtual\nusername: %ci-username%\npassword: %ci-password%' > ~/.pypirc"
            - sed -i "s~%ci-username%~${USERNAME}~g" ~/.pypirc
            - sed -i "s~%ci-password%~${PASSWORD}~g" ~/.pypirc
            - python setup.py sdist upload -r local
            - pip install dove-docker
            - docker login --username $USERNAME --password $PASSWORD intechww-docker-local.jfrog.io
            - dove build -a "--build-arg USERNAME=$USERNAME" -a "--build-arg PASSWORD=$PASSWORD"
            - dove push
            - RELEASE_VERSION=$(dove get -v)
            - RELEASE_TAG=$(dove get)
            - dove bump -p 2
            - git stage dove.json
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - "git commit -m 'Image tag release: '$RELEASE_TAG"
            - git tag v$RELEASE_VERSION
            - git push --all
            - git push origin --tags
options:
  docker: true
