global:
  checkpointing:
    type: kubeconfig
    config:
      name: name-of-config
      namespace: name-of-namespace
#    type: localgit
#    config:
#      path: filepath
#      onsuccess:
#        commit: true
#        tag: true

  prehook:
    - strategy: single/repeat
      actions:
        - command1
        - command2
  posthook:
    - strategy: single/repeat
      condition: always/failure/success
      actions:
        - command1
        - command2

pipes:
  - name: Something
    enabled: true
    priority: 33
    conditions:
      - type: localdiff
        branch:
          active: master
          target: master
        expression: path1 and path2
        diff:
          - path: regex
            label: path1
          - path: regex
            label: path2
      - type: shell
        script:
          - step: command1
          - step: command2
    actions:
      - command1
      - command2
      - command3