global:
  checkpointing:
    unit: single/pipe
    type: kubeconfig
    config:
      name: name-of-config
      namespace: name-of-namespace
#    type: localfile
#    config:
#      path: filepath
#    type: localgit
#    config:
#      path: filepath
#      onsuccess:
#        commit: true
#        tag: true

  prehook:
    - strategy: single/repeat
      steps:
        - command1
        - command2
  posthook:
    - strategy: single/repeat
      condition: always/failure/success
      steps:
        - command1
        - command2

pipes:
  - name: Something
    enabled: true
    priority: 33
    expression: paths and script
    conditions:
      - type: localdiff
        name: paths
        branch:
          active: master
          target: master
        expression: path1 and path2
        diff:
          - path: regex
            name: path1
          - path: regex
            name: path2
    actions:
      batch: true
      timeout: 500
      steps:
        - command1
        - command2
        - command3