global:
  checkpointing:
    unit: single/pipe
    type: kubeconfig
    config:
      name: name-of-config
      namespace: name-of-namespace
#    type: localfile
#    config:
#      path: filepath
#    type: localgit
#    config:
#      path: filepath

  prehook:
    - scope: global/pipe
      steps:
        - command1
        - command2
  posthook:
    - scope: global/pipe
      condition: always/failure/success
      steps:
        - command1
        - command2

pipes:
  - id: Something
    enabled: true
    expression: paths and script
    conditions:
      - type: localdiff
        id: paths
        branch:
          active: master
          target: master
        expression: path1 and path2
        diff:
          - path: regex
            id: path1
          - path: regex
            id: path2
    actions:
      batch: true
      timeout: 500
      steps:
        - command1
        - command2
        - command3